### ISSUE TITLE
本地知识库构建报错

### ISSUE THREAD

**Issue by 13875892872** [InternLM/HuixiangDou#206]
<img width="768" alt="d3cc3cbd9e428c9cdb7c75bf782ddcd" src="https://github.com/InternLM/HuixiangDou/assets/57122643/b8445609-017f-4cd0-87df-e49b29fd62ca">
运行python3 -m web.main，在web端上传文档报错。

**Comment by tpoisonooo** [comment]
Fixed in wechat.
