### ISSUE TITLE
fetch的服务需要怎么配置才能正常起起来

### ISSUE THREAD

**Issue by Modas-Li** [InternLM/HuixiangDou#26]
## error log | 日志或报错信息 | ログ
![image](https://github.com/InternLM/HuixiangDou/assets/40042370/8c0a7c34-e0b9-47e5-ab84-3307abe88d2d)
![image](https://github.com/InternLM/HuixiangDou/assets/40042370/728bf1e8-bbc5-4031-bff3-53ccfb2fed4f)

## context | 编译/运行
环境 | バックグラウンド
python 3.10
## how to reproduce | 复现步骤 | 再現方法
按照文档进行

**Comment by tpoisonooo** [comment]
光看截图，我都不知道你到哪一步了...   扫微信聊一下？

**Comment by tpoisonooo** [comment]
你的  175.xxxx ，外网能连上么。

**Comment by Modas-Li** [comment]
设置成localhost
