### ISSUE TITLE
非Hybrid-LLM环境，使用deepseek远程模型运行web-demo报错

### ISSUE THREAD

**Issue by SchweitzerGAO** [InternLM/HuixiangDou#277]
## error log | 日志或报错信息 | ログ
![7](https://github.com/InternLM/HuixiangDou/assets/64410968/e3c7c0e1-04de-4db8-a274-7e5b91171393)

## context | 编译/运行环境 | バックグラウンド
Intern Studio 30% A100 with built-in Huixiangdou environment
## how to reproduce | 复现步骤 | 再現方法
1. 按照[实战营教程](https://github.com/InternLM/Tutorial/blob/camp2/huixiangdou/readme.md#32-%E4%BD%BF%E7%94%A8%E8%BF%9C%E7%A8%8B%E6%A8%A1%E5%9E%8B) 配置`config.ini`
2. 运行`python3 -m tests.test_query_gradio`
3. 打开http://127.0.0.1:7860  输入“茴香豆如何在微信群部署？”
4. 在终端看到报错信息

## more | 其他 | その他
1. 在上面第2步加了`--standalone` 也无济于事
2. Hybrid-LLM环境下可以正常运行，不过似乎没有调用deepseek API

**Comment by tpoisonooo** [comment]
1. 参考 FAQ
  ![image](https://github.com/InternLM/HuixiangDou/assets/7872421/146925da-a1dd-43ca-ae78-634dd1ff1721)

2. 如果不行，pdb 这行  https://github.com/InternLM/HuixiangDou/blob/9f459614dc9139f6d1bd9f6ea39a6212963605a9/huixiangdou/service/llm_server_hybrid.py#L514C25-L514C36

   这个 remote deepseek 实现就  4 行，怎么也能 debug 出来

```bash
    def call_deepseek(self, prompt, history):
        client = OpenAI(
            api_key=self.server_config['remote_api_key'],
            base_url='https://api.deepseek.com/v1',
        )

        messages = build_messages(
            prompt=prompt,
            history=history,
            system='You are a helpful assistant')  # noqa E501

        logger.debug('remote api sending: {}'.format(messages))
        completion = client.chat.completions.create(
            model=self.server_config['remote_llm_model'],
            messages=messages,
            temperature=0.1,
        )
        return completion.choices[0].message.content
```

**Comment by tpoisonooo** [comment]
跑了当前版本没问题。
![image](https://github.com/InternLM/HuixiangDou/assets/7872421/22a59453-4046-4d40-abbe-2be82b44c02f)

检查一下这些配置是否有错：

![image](https://github.com/InternLM/HuixiangDou/assets/7872421/e1429acb-99a1-40c9-b303-44ddc74d1c61)

**Comment by SchweitzerGAO** [comment]
好的，我去测一下main分支，实战营教程文档最开始让切换到另一个分支去了

**Comment by tpoisonooo** [comment]
> 好的，我去测一下main分支，实战营教程文档最开始让切换到另一个分支去了

fixed  https://github.com/InternLM/Tutorial/pull/695

**Comment by SchweitzerGAO** [comment]
main分支可以正常运行，感谢大佬
