### ISSUE TITLE
ValueError: Cannot decide self.index type

### ISSUE THREAD

**Issue by deep-practice** [InternLM/HuixiangDou#346]
## error log | 日志或报错信息 | ログ
`2024-08-10 13:06:05.213 | INFO     | __main__:analyze:175 - token histogram, length count 3369, avg 225.98, median 240
0-56  10.36%
56-112  9.68%
112-168  9.68%
168-224  15.08%
224-280  19.09%
280-336  18.64%
336-392  11.69%
392-448  4.63%
448-504  1.07%
504-560  0.06%
560-616  0.03%

08/10/2024 13:06:05 - [INFO] -faiss.loader->>>    Loading faiss with AVX2 support.
08/10/2024 13:06:05 - [INFO] -faiss.loader->>>    Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
08/10/2024 13:06:05 - [INFO] -faiss.loader->>>    Loading faiss.
08/10/2024 13:06:05 - [INFO] -faiss.loader->>>    Successfully loaded faiss.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3369/3369 [00:34<00:00, 99.06it/s]
2024-08-10 13:06:40.141 | INFO     | huixiangdou.primitive.file_operation:summarize:143 - 累计555文件，成功438个，跳过0个，异常117个
Traceback (most recent call last):
  File "/root/.conda/envs/demo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.conda/envs/demo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/projects/HuixiangDou/huixiangdou/service/feature_store.py", line 384, in <module>
    retriever = cache.get(config_path=args.config_path, work_dir=args.work_dir)
  File "/root/projects/HuixiangDou/huixiangdou/service/retriever.py", line 273, in get
    retriever = Retriever(config_path=config_path,
  File "/root/projects/HuixiangDou/huixiangdou/service/retriever.py", line 48, in __init__
    self.faiss = Faiss.load_local(dense_path)
  File "/root/projects/HuixiangDou/huixiangdou/primitive/faiss.py", line 184, in load_local
    raise ValueError('Cannot decide self.index type')
ValueError: Cannot decide self.index type`
## context | 编译/运行环境 | バックグラウンド
InternStudio cuda12.2 HuixiangDou main版本
## how to reproduce | 复现步骤 | 再現方法
根据readme进行操作：
1.mkdir repodir
2.git clone https://github.com/open-mmlab/mmpose --depth=1 repodir/mmpose
3.#把 repodir 的特征保存到 workdir，把正反例阈值更新进 `config.ini`
mkdir workdir
4.python3 -m huixiangdou.service.feature_store
![image](https://github.com/user-attachments/assets/e0cf6973-3e3b-4e0d-ba5b-ce0e260a0a94)

**Comment by tpoisonooo** [comment]
我来尝试复现下。

**Comment by tpoisonooo** [comment]
你方便做个这操作么？

```bash
import faiss
index = faiss.read_index('/path/to/your/embedding.faiss')
print(type(index))
```

**Comment by deep-practice** [comment]
type(index): <class 'faiss.swigfaiss.IndexFlat'>

**Comment by tpoisonooo** [comment]
> type(index): <class 'faiss.swigfaiss.IndexFlat'>

哦，类型判少了。 我来修一下。

**Comment by tpoisonooo** [comment]
@deep-practice   你环境变量里有个  `FAISS_NO_AVX2` 生效，导致 `import faiss.swigfaiss` ，导致后面 class 类型没有匹配，最后报错。

实际 internstudio  cpu 都是支持 avx2 的，不知为啥开这个选项。

**Comment by tpoisonooo** [comment]
更一下代码，应该好了。

**Comment by loki-zhou** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/HuixiangDou/huixiangdou/service/feature_store.py", line 384, in <module>
    retriever = cache.get(config_path=args.config_path, work_dir=args.work_dir)
  File "/root/HuixiangDou/huixiangdou/service/retriever.py", line 273, in get
    retriever = Retriever(config_path=config_path,
  File "/root/HuixiangDou/huixiangdou/service/retriever.py", line 48, in __init__
    self.faiss = Faiss.load_local(dense_path)
  File "/root/HuixiangDou/huixiangdou/primitive/faiss.py", line 176, in load_local
    raise ValueError('Cannot decide self.index type {}, open https://github.com/InternLM/HuixiangDou/issues/346 for hotfix'.format(type(index)))
ValueError: Cannot decide self.index type <class 'faiss.swigfaiss_avx2.IndexFlat'>, open https://github.com/InternLM/HuixiangDou/issues/346 for hotfix
```

```
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
>>> index = faiss.read_index('embedding.faiss')
>>> print(type(index))
<class 'faiss.swigfaiss_avx2.IndexFlat'>
```

**Comment by loki-zhou** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/root/HuixiangDou/huixiangdou/service/feature_store.py", line 384, in <module>
>     retriever = cache.get(config_path=args.config_path, work_dir=args.work_dir)
>   File "/root/HuixiangDou/huixiangdou/service/retriever.py", line 273, in get
>     retriever = Retriever(config_path=config_path,
>   File "/root/HuixiangDou/huixiangdou/service/retriever.py", line 48, in __init__
>     self.faiss = Faiss.load_local(dense_path)
>   File "/root/HuixiangDou/huixiangdou/primitive/faiss.py", line 176, in load_local
>     raise ValueError('Cannot decide self.index type {}, open https://github.com/InternLM/HuixiangDou/issues/346 for hotfix'.format(type(index)))
> ValueError: Cannot decide self.index type <class 'faiss.swigfaiss_avx2.IndexFlat'>, open https://github.com/InternLM/HuixiangDou/issues/346 for hotfix
> ```
> 
> ```
> Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import faiss
> >>> index = faiss.read_index('embedding.faiss')
> >>> print(type(index))
> <class 'faiss.swigfaiss_avx2.IndexFlat'>
> ```

无脑跑ReadME， 自己没有设置环境变量， 中间有做
```
ln -s swigfaiss.py swigfaiss_avx2.py
```
