### ISSUE TITLE
the main_args is undefined in huixiangdou/server.py

### ISSUE THREAD

**Issue by leagend** [InternLM/HuixiangDou#364]
## error log | 日志或报错信息 | ログ
python3 -m huixiangdou.server                   
Traceback (most recent call last):
  File "/root/.conda/envs/huixiangdou/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.conda/envs/huixiangdou/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/group_share/jing/backup/huixiangdou/huixiangdou/server.py", line 135, in <module>
    start_llm_server(config_path=main_args.config_path)
NameError: name 'main_args' is not defined
## context | 编译/运行环境 | バックグラウンド
python 3.10
## how to reproduce | 复现步骤 | 再現方法

1. go to source code https://github.com/InternLM/HuixiangDou/blob/main/huixiangdou/server.py#L130-L135
```
if __name__ == '__main__':
    args = parse_args()
    # start service
    if args.standalone is True:
        # hybrid llm serve
        start_llm_server(config_path=main_args.config_path)   <-- the main_args here is undefined
```
3.
4.

## more | 其他 | その他
It failed the command line"python3 -m huixiangdou.server "

**Comment by tpoisonooo** [comment]
Thanks and the bug fixed, please feel free to send a Pull Request.

**Comment by tpoisonooo** [comment]
@leagend

**Comment by tpoisonooo** [comment]
merged.

**Comment by leagend** [comment]
close the issue as fixed.
