### ISSUE TITLE
OpenXlab上面的茴香豆能够拒绝回答政治、暴力相关的问题，是通过什么方式实现的呢？提示词吗？

### ISSUE THREAD

**Issue by deep-practice** [InternLM/HuixiangDou#367]
OpenXlab上面的茴香豆能够拒绝回答政治、暴力相关的问题，是通过什么方式实现的呢？提示词吗？

**Comment by tpoisonooo** [comment]
https://github.com/InternLM/HuixiangDou/blob/8a96608afa08903000bdb4b10dcd1135ccdfc737/huixiangdou/service/prompt.py#L45
