### ISSUE TITLE
gradio界面显示答案非常非常慢，需要100多，且不是流式输出

### ISSUE THREAD

**Issue by deep-practice** [InternLM/HuixiangDou#368]
## how to reproduce | 复现步骤 | 再現方法
显卡：InternStudio 30% A100
gradio版本：4.42.0
![error_page](https://github.com/user-attachments/assets/02d19c30-3317-4715-b40b-20c0189f353d)

**Comment by deep-practice** [comment]
针对知识库中没有提到的内容进行提问，会胡言乱语。这种是通过优化提示词来减少这种幻觉吗？
![image](https://github.com/user-attachments/assets/1b53cdc6-1809-4015-a6fd-c167f520afb5)

**Comment by tpoisonooo** [comment]
1. **不是流式**。InternStudio 是个 1 虚 6 的虚拟机，io 和 网络都极慢， 换纯 CPU 版跑本机再体验一下？
2. **胡言乱语**。换个 LLM

**Comment by tpoisonooo** [comment]
streaming 对网络要求更高。

**Comment by tpoisonooo** [comment]
https://github.com/InternLM/HuixiangDou/blob/8a96608afa08903000bdb4b10dcd1135ccdfc737/huixiangdou/gradio.py#L138  看下源码，当选择 `chat_in_repo` 时， `yield` 增量回答，如果你看到的不是流式，那大概是网络问题。

**Comment by deep-practice** [comment]
换了siliconcloud的qwen1.5-110B，效果直线提升。
