### ISSUE TITLE
部署web版知识库的时候报缺失ner_file参数

### ISSUE THREAD

**Issue by l241025097** [InternLM/HuixiangDou#400]
## error log | 日志或报错信息 | ログ

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/project/web/proxy/main.py", line 376, in <module>
    process()
  File "/workspace/project/web/proxy/main.py", line 357, in process
    build_feature_store(fs_cache, msg.payload)
  File "/workspace/project/web/proxy/main.py", line 205, in build_feature_store
    fs.initialize(files=files, work_dir=workdir)
TypeError: FeatureStore.initialize() missing 1 required positional argument: 'ner_file'

## context | 编译/运行环境 | バックグラウンド

docker

## how to reproduce | 复现步骤 | 再現方法

1. python3 -m huixiangdou.service.llm_server_hybrid --config_path config-cpu-local.ini
2. python3 -m web.main
3. python3 -m web.proxy.main

## more | 其他 | その他

前2步都正常，第3步报错：TypeError: FeatureStore.initialize() missing 1 required positional argument: 'ner_file'。
我去看了源码：
```
def initialize(self, files: list, ner_file:str, work_dir: str):
        """Initializes response and reject feature store.

        Only needs to be called once. Also calculates the optimal threshold
        based on provided good and bad question examples, and saves it in the
        configuration file.
        """
        logger.info(
            'initialize response and reject feature store, you only need call this once.'  # noqa E501
        )
        self.preprocess(files=files, work_dir=work_dir)
        # build dense retrieval refusal-to-answer and response database
        documents = list(filter(lambda x: x._type != 'code', files))
        chunks = self.build_dense(files=documents, work_dir=work_dir)

        codes = list(filter(lambda x: x._type == 'code', files))
        self.build_sparse(files=codes, work_dir=work_dir)
        self.build_inverted_index(chunks=chunks, ner_file=ner_file, work_dir=work_dir)
```
ner_file这个参数确实没有传值进来，不知道这个值在这个方法里是否是必须的。如果不是必须的，是不是应该写成：
```
def initialize(self, files: list, work_dir: str, ner_file:str=None):
        pass
```

**Comment by tpoisonooo** [comment]
之前乱乱的，现在内部版本已经简化（年底开源）。

**Comment by l241025097** [comment]
> 之前乱乱的，现在内部版本已经简化（年底开源）。

好的，期待新版开源。
